[package]
name = "nannou"
version ="0.14.1"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A Creative Coding Framework for Rust."
readme = "README.md"
keywords = ["creative", "sketch", "graphics", "audio"]
license = "MIT"
repository = "https://github.com/nannou-org/nannou.git"
homepage = "https://github.com/nannou-org/nannou"
edition = "2018"

[features]
default = ["notosans"]

[dependencies]
cgmath = { version = "0.17", features = ["serde"] }
conrod_core = "0.70"
conrod_wgpu = "0.70"
conrod_winit = "0.70"
daggy = "0.6"
find_folder = "0.3"
futures = { version = "0.3", features = ["executor", "thread-pool"] }
image = "0.23"
lyon = "0.15"
noise = "0.6"
notosans = { version = "0.1", optional = true }
num_cpus = "1"
palette = "0.5"
pennereq = "0.3"
rand = { version = "0.7", features = ["small_rng"] }
rusttype = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.5"
walkdir = "2"
wgpu = "0.6"
winit = "0.22"
